services:
  db:
    image: mysql:8.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: 'fullcycle'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - mynetwork
    ports:
      - "3306:3306"

  app:
    build: 
      context: ./app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: bash -c "npm install && node index.js"    
    networks:
      - mynetwork
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    tty: true
    depends_on:
      - db

  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    networks:
      - mynetwork
    ports:
      - "8080:80"
    depends_on:
      - db
      - app

networks:
  mynetwork:
    driver: bridge
